Update modulizer polymer fixture

diff --git a/packages/modulizer/fixtures/packages/polymer/source/bower_components/iron-fit-behavior/.travis.yml b/packages/modulizer/fixtures/packages/polymer/source/bower_components/iron-fit-behavior/.travis.yml
--- a/packages/modulizer/fixtures/packages/polymer/source/bower_components/iron-fit-behavior/.travis.yml
+++ b/packages/modulizer/fixtures/packages/polymer/source/bower_components/iron-fit-behavior/.travis.yml
@@ -1,5 +1,5 @@
 language: node_js
-sudo: required
+sudo: 'false'
 before_script:
   - npm install -g polymer-cli
   - polymer install --variants
@@ -7,24 +7,25 @@ before_script:
     npm run update-types && git diff --exit-code || (echo -e
     '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
     update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
     - secure: >-
-        L4lSnuQZDY+YcXYzBZSRKjJJ1rZf18Lc/8YDgQPfkMkAItrRHGR8vblBoKiPAmtvgNxztcpZxAXTiDy1vAeVv54QnX9b1JsuOs7rrQxB4BS04Dj7LdT6DDu1p/V09MJBN11lzLVxgpxljbumwGWE4gfpDl2+rjbBt7cRV5VkVnE=
+        IRn7Bu0Iq9etV/e71Lt3D9FRwVYB6lx8ItB9qk6Tj0FdmtpZ0PIKjTQ08QnbNHinl4xMkeJWs41qPk8LpOig2LHd7AmXnomRwHck1+7oJyIqTMf9fsbZ8BkdAz8RPr0OmiTVsjAZaFaI9YVc9y9DyfD8DGO51mWdpUCfr/S2+Hw=
     - secure: >-
-        H7dHZ9FQvJszK2UMNZJiZmzOPET3muO/XvlkUc1x3KcUlV5/tD/404V05XfFMowH7DavHFYleZkb89deYjq9PHncO9c4bp4SHD7HKN4FaGyhzfpXjg66v3dZH/OcERjaas337uUE2jo/x1jCq4HJCz2bMVh+bvd4du1C/2OWarc=
-node_js: stable
+        ZJDnPya7VyGKCUiaG1VfoT2GWRXDPt33+uFgLxIx3ahZu/Mlw5jy5vu9Y/qQldHAdGceY19wmXhdHsnQBKmDjE4MDSVl7FDVV5eUstsudoovx+ul9MsbdGfBXKT6C3bATqPpQ+ML8hMeuJSQ4AlbY7+KhpVEVi4ko8uaDERdOWc=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
-  sauce_connect: true
+  chrome: stable
 script:
   - xvfb-run polymer test
   - >-
     if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
     fi
 dist: trusty
+cache:
+  directories:
+    - node_modules
